### ISSUE TITLE
validations are broken

### ISSUE THREAD

**Issue by kernow** [benpickles/js-model#1]
Using jquery 1.3.1 when running the validation example in the read me post.valid() returns false when all the validations are met. Is there a requirement for jquery 1.4+?

**Comment by benpickles** [comment]
jQuery 1.4+ is required - though it's only really needed for REST persistence otherwise everything else works fine. Try this: http://gist.github.com/353675

It sounds like you're using old syntax or running an older version of js-model - there was a slight change in syntax for declaring models and adding errors. What version are you running?

**Comment by benpickles** [comment]
closing
