### ISSUE TITLE
unsafe multithread access to Model.collection

### ISSUE THREAD

**Issue by jlsync** [benpickles/js-model#12]
If you have a large collection of Projects and run something like,
    Project.each(function(){ Project.remove(this)});
you'll find that 
    Project.count()
is not zero. I'm guessing there is concurrent activity between the index location and then splicing in Model.remove.

Maybe the collection could be made an object keyed on id:  or some other primary key attribute to fix this problem.

**Comment by benpickles** [comment]
yeh `remove` is splicing the collection array so now the counter in `each` is wrong. you can get around this by iterating backwards over the array like so:

```
var Project = Model("project", {
  removeAll: function() {
    var all = this.all()

    for (var i = all.length; i >= 0; i--) {
      Project.remove(all[i])
    }

    return this
  }
})
```

i'm not sure it's something that can be "fixed" - making the collection an object keyed by id is a possible solution but it falls down in other areas. there is now the concept of a uid which might be key. it's worth thinking about though - let me know if you find a solution :)

**Comment by jlsync** [comment]
instead of using splice perhaps you could use

```
 delete collection[i]
```

this would retain the original index locations but would also require changes elsewhere.

One benefit of using the id as the primary key is faster lookups.

**Comment by benpickles** [comment]
some sort of id-based lookup sounds great but very difficult to maintain.

i fear it's mostly an app-specific problem. perhaps some patterns will emerge, it wouldn't be difficult to write a "module" to override current behaviour and include it on specific models.

**Comment by benpickles** [comment]
got an email of your response but it hasn't popped up here?

(i meant that maintaining an index is probably an app-specific issue.)

the only issue with the above `removeAll` function is that it has to reference the original class rather than it's "scope" so i had to add a class map - which might come in handy for some other things...

http://github.com/benpickles/js-model/compare/remove-all

**Comment by jlsync** [comment]
removeAll looks like a useful addition to the api. thanks. 

but it still doesn't solve the problem that regular usage of Model.remove is unsafe.

**Comment by jlsync** [comment]
looks like backbone separately maintains primary key indexes and a length attribute, but still seems to be using an array for storage.

http://github.com/documentcloud/backbone/blob/master/backbone.js#L430-442

**Comment by jlsync** [comment]
I have two possible fixes for this problem,

1/ 
http://github.com/jlsync/js-model/commit/29e629bf99ea985781f70586113647270b69cc59

```
 delete array[i]
 array = array.filter(function(i){ return i== undefined});
```

seems to be the fastest way to remove elements from an array of objects, at least for elements at the beginning of the array. So fast that I'm not seeing any race condition problems with the original:
     Project.each(function(){ Project.remove(this)});

2/
http://github.com/jlsync/js-model/commit/f27e39454295b70d4986ce3358fd6bf9267fb558

re-implement Model.collection with an object {} instead of an array [] with model.id() being the key.

I'm guessing it's generally all-round faster and Model.remove is much safer.

**Comment by jlsync** [comment]
I notice supermodel uses an object {}  instead of an array []. 
http://github.com/maccman/supermodel-js/blob/master/supermodel.js

**Comment by benpickles** [comment]
it's not a race condition you're seeing, it's just what happens when you delete from an array during a loop. here's the same behaviour in ruby:

```
array = [1, 2, 3, 4, 5]
array.each_with_index do |n, i|
  array.delete i
end

p array
# => [3, 4, 5]
```

that said, i agree that this is not what you might expect, [this commit](http://github.com/benpickles/js-model/compare/safe-each) fixes the issue.

your `filter()` method has the same issue but it's hidden as you're reassigning the collection array whilst the each loop continues to reference the original collection array.

the collection can't be represented as an object keyed by id because models without an id are allowed in a collection but it would definitely be worth investigating creating an id-based index for use with `find()`.

**Comment by jlsync** [comment]
excellent, thanks for fix.

**Comment by benpickles** [comment]
just to let you know, the fix is now in master
